### ISSUE TITLE
keep in foreground?

### ISSUE THREAD

**Issue by rsidd** [pelya/xserver-xsdl#10]
The big disadvantage with the xserver vs a vnc viewer is that, if the x server is killed, the session is gone.   So far I worked around it by renicing it to -20 and doing a cron job to adjust the x server's oom_adj and oom_score_adj in /proc, but it just got killed again.  (Android doesn't seem to kill the chrooted linux applications, only its own apps.) I read that if the app includes a "service", you can keep it in the foreground using startForeground() -- is that a possibility here?  Thanks!
http://developer.android.com/reference/android/app/Service.html#startForeground%28int,%20android.app.Notification%29

**Comment by pelya** [comment]
Well Xserver is starting dummy Android service inside version 1.11.12, I don't know if that will help or not. Anyway, there's nothing more that I can do to prevent it to be killed, so I'm closing this bug.

**Comment by rsidd** [comment]
Thanks.  I think it works, at least it's much better than earlier.  I cycled 7-8 other apps while this was in the background, let it sleep for a while, etc, it stayed alive.  And it hasn't died since your last update.
