### ISSUE TITLE
XSDL command line doesn't seem to be working

### ISSUE THREAD

**Issue by kitsunyan** [pelya/xserver-xsdl#100]
Hi! I'm using the latest XSDL from market (1.11.40). It seems that any command line arguments I pass under `Specify command line parameters` menu don't take effect. For instance, specifying the display or using [-screen](https://github.com/pelya/xserver-xsdl/issues/12) option (which also should probably [remove the configuration menu](https://github.com/pelya/commandergenius/blob/4d6a8dcd8823c82a380adb9e3ad77a160f8c44f1/project/jni/application/xserver/main.c#L77)) don't take any effect.

**Comment by kitsunyan** [comment]
After reading the code, I understood finally. For some reason all spaces are replaced with double spaces, while line breaks are replaced with space! That means, I need to use line breaks to separate arguments. Like this:

```
XSDL
-nohelp
-screen
1920x1080x16
```

Hope someone will find this helpful. For instance, specifying the `-screen` indeed [removes the configuration menu](https://github.com/pelya/xserver-xsdl/issues/87) and timeout.

**Comment by gahu777** [comment]
> After reading the code, I understood finally. For some reason all spaces are replaced with double spaces, while line breaks are replaced with space! That means, I need to use line breaks to separate arguments. Like this:
> 
> ```
> XSDL
> -nohelp
> -screen
> 1920x1080x16
> ```
> 
> Hope someone will find this helpful. For instance, specifying the `-screen` indeed [removes the configuration menu](https://github.com/pelya/xserver-xsdl/issues/87) and timeout.

thanks a lot ! where i can find other commandline parameters like autodetect orientation?
