### ISSUE TITLE
Restart loop

### ISSUE THREAD

**Issue by anonimo82** [pelya/xserver-xsdl#102]
Hello everyone.
I know this has been reported more than once, by many people.
Just want to clean up a bit and have an update on this.

Now, the problem is: I can't run Xserver XSDL, because, after the countdown, the apps switch to a view which displays a restarting messsage.

Just for the records, I've been able to use it until some months ago, but now, I have this problem as many more others have.

I'm running LineageOS Pie, SM-G900F.

I didn't install anything from Linux Deploy yet, because I first want to be sure this is solved.

Excuse me for duplicated issue, I hope this will be the "update log" for this kind of problem.

Thanks in advance for any help.

**Comment by pelya** [comment]
Fixed in 1.20.41
