### ISSUE TITLE
Capture audio/video

### ISSUE THREAD

**Issue by anonimo82** [pelya/xserver-xsdl#104]
Hello everyone.
Is there any way to capture audio/video from device's mic/cam?
I'd also like to record "internal" audio/video, eg the sound being played and the screen.

Is this possible?

My device is ZE551ML, Lollipop stock, Debian stable, XFCE, installed as folder, using XSDL, chroot container, I mounted storage folders for local and sd memory and I use pulseaudio.

**Comment by pelya** [comment]
No. X protocol does not provide camera interface, and I don't plan to increase permission list needlessly.
