### ISSUE TITLE
Please, why you did not released new. apk on Github by using changes on source code here?

### ISSUE THREAD

**Issue by JanuszChmiel** [pelya/xserver-xsdl#105]
Please, does this source code contain more changes than officially available Xserver XSDL on GOogle Play? If yes, why you have decided not to publish updated app on GOogle pLay store?
You would also send .apk file here on Github, if you do not want to update app on Google Play store.

**Comment by pelya** [comment]
Because it does not work yet. It's pointless to release non-working app.

**Comment by JanuszChmiel** [comment]
I Am very sorry. I will patiently wait. I know, that like amateur, I can not imagine how complex is to develop such complex C native application. I will patiently wait and I AM ready to test first alpha release. By The way.
Do you have some tips how to prevent file system severe corruption when testing such complex apps when I Am forced to unplug battery from Android device? If many auto reboots occur, or if Android can not load?
Or The best strategy is test on The simulator first? If system crash after battery is plugged in again. Is it possible to always repair The device by using recovery build in console boot menu by running factory reset?
Or in some cases, chip can hardware get corrupted? I know, that it is always much more better to shut down device by using its build in software routine. But if native C code is being debugged, it is necessary to use those aggressive approach like unplug battery is.
Thank you very much for yours time.
By The way. I can really try to debug with you.

**Comment by pelya** [comment]
Android is designed in a way that you cannot damage your phone by running
an app (unless you root it). If your phone gets damaged, it's most probably
a hardware failure and should be replaced by warranty.

The app can abuse CPU or write excessive amount of data to flash, which
will decrease it's lifetime, but you generally will notice it because your
phone will become hot and unresponsive.

And yes, factory reset fixes everything except hardware failure.

**Comment by pelya** [comment]
Update released to Play Store

**Comment by JanuszChmiel** [comment]
Very well done. Thank you very much for yours complex programmers work. I will test this release.
