### ISSUE TITLE
Build in Pulseaudio server is not compatible with Speech-dispatcher and with its ESPEAK speech synthesizer.

### ISSUE THREAD

**Issue by JanuszChmiel** [pelya/xserver-xsdl#107]
Dear specialists,
Would please somebody of us try to look at The Debian Buster ARM64 Bit and Speech-dispatcher issue? When Espeak is installed?
Steps to reproduce The issue.
1. Download Userland from Google Play store.
2. Install Debian distribution. Use SSH protocol.
When system is ready.
3. su
4. apt update
apt install espeak
apt install speech-dispatcher
exit
export PULSE_SERVER=tcp:127.0.0.1:4712
Run Xserver XSDL and let system to quitly reside at this Window.
From SSH connected device type
spd-say "some testing text."
Speech will be very interrupted.
Yours PUlseaudio is perfect. I AM very sorry, that I have thought, that it is slow. No. Other apps including standalone Espeak command tool work perfectly. There is complex issue between speech-dispatcher and yours variant of build in PUlseaudio for Xserver XSDL.
I have tested on The several devices and The problem is The same. You can choose more detailed debug log for Speech-dispatcher to determine which problem can cause so big interruption.
I have even tried to use Voiceman latest version but it do not work at all. No speech. It is very probably not configured to stream by using aonly libraryes. I have tried to change Speech-dispatcher configuration file to switch from Pulseaudio to Libao. But speech is still interrupted.
If I can do some steps to try to find The cause of this behaviour, please let Me know.
Pulseaudio for Termux do not make this problems. But I would like to use XserverXSDL and yours integrated Pulseaudio to save memory and because I will mainly run X applications.
Any help will be very welcomed. You are elite C programmer, I have looked at The various places on Github and I Am sure, that if you will not find The cause, nobody have this chance.
Thank you very much for yours discussion and for some advices. Sure, I Am ready to help as I can.

**Comment by JanuszChmiel** [comment]
I have sox package installed on Debian Buster ARM64 which run by using Userland. Espeak is The fastest speech engine, which allocates The less MB of RAm. There is no other multilanguage engine available for free and IBM VVIA VOice outloot and other allocates much more RAM, because it uses high quality databases with voice samples and algorithm is allocating much more CPu cycles. 
Thank you veryvery much for yours time.

**Comment by pelya** [comment]
Should be fixed in 1.20.41
