### ISSUE TITLE
Portrait version has wrong aspect ratio [please re-open]

### ISSUE THREAD

**Issue by cbm755** [pelya/xserver-xsdl#11]
I tried 1.11.09-portrait (from sf.net).  My device (gt5110) has 1280x800 display.

The xserver was in portrait orientation but with the resolutions switched and not matching the physical pixels (it used 1280 for the horizontal res and 800 for the vertical---exactly backwards).

It was also written reversed on the mode selection screen compared to the hardcoded options.  The hardcosed options had the correct aspect but none of them matched my physical display size.

I see quite a few changes to the mode selection bit but don't have build environment setup to test.  is it possible to switch to portrait in prefences menus or in some config file?  otherwise happy to test if you roll a new portrait apk.

**Comment by pelya** [comment]
Here you go:
http://sourceforge.net/projects/libsdl-android/files/apk/XServer-XSDL/XServer-XSDL-1.11.12-portrait.apk/download
I didn't think someone would actually need portrait version, it has more resolutions, and slightly broken setup UI, but it's still manageable.

**Comment by cbm755** [comment]
Ok, sorry for the delay, this version has the same issue:

![screenshot_2014-02-25-20-46-32](https://f.cloud.github.com/assets/818622/2340970/818c47fc-a4ce-11e3-8b32-012fc4b456dc.png)

In this next one, note the first column (the native res of "800x1280" and fractions thereof) are in the wrong order compared to the hardcoded resolutions such as 1280x1024).  I'm convinced this is the problem (or at least a symptom)

![screenshot_2014-02-25-20-47-55](https://f.cloud.github.com/assets/818622/2340971/818e22f2-a4ce-11e3-9eaf-2534ca21ff1d.png)

![screenshot_2014-02-25-20-55-41](https://f.cloud.github.com/assets/818622/2340972/81926790-a4ce-11e3-8b19-43a7554a10ca.png)

For comparison, here is it running at 1280x720 (one of the non-native hardcoded choices), which at least displays correctly.

![screenshot_2014-02-25-20-51-52](https://f.cloud.github.com/assets/818622/2341231/4fbc5d7e-a4d4-11e3-89f9-959d0c8639a6.png)

**Comment by cbm755** [comment]
I don't see anyway to re-open this...

**Comment by pelya** [comment]
Okay I see.

**Comment by pelya** [comment]
It took me long enough, but I've finally fixed all issues (I think). Please try this new version:
http://sourceforge.net/projects/libsdl-android/files/apk/XServer-XSDL/XServer-XSDL-1.11.14-portrait.apk

**Comment by cbm755** [comment]
Yes, fixed thanks!
