### ISSUE TITLE
Can't enable 24bpp mode

### ISSUE THREAD

**Issue by ArcadeHacker** [pelya/xserver-xsdl#114]
When enabling 24bpp mode the app wont start: Error: X server failed to launch

Tested in 3 different Android 9 devices.

**Comment by dms93** [comment]
Hi!
With the latest version it's possible to start X server, but when i execute gui applications, i can't see a real difference.  
I don't know if this is a problem or i need to setup something.

**Comment by dms93** [comment]
Update.
Before the 24bpp mode It wasn't possible to show Java/Swing GUI (I work with this now). It drawed a yellow rectangle, now it can be possible.

**Comment by pelya** [comment]
Because the difference is hard to notice.

https://www.cambridgeincolour.com/tutorials/bit-depth.htm

If you open that page in XSDL 16bpp, both 24bpp and 16bpp images shoud look
the same.

**Comment by dms93** [comment]
Ok!  Thanks for the information.

**Comment by ArcadeHacker** [comment]
Thanks for fixing this!
