### ISSUE TITLE
-screen option on XSDL cmd line

### ISSUE THREAD

**Issue by cbm755** [pelya/xserver-xsdl#12]
preferences menu system allows me to change the XSDL cpmmand line.  But if I add -screen 1280x800x24 (or 640x480x24 or whatever) than I get a black screen rather than the blue & white help screen about setting up $DISPLAY.

Fwiw, ":1" works to change X server port.

If I connext to the black screen Xserver, I think I get crashes from client apps but can double-check...

**Comment by cbm755** [comment]
ok, xrandr reports server is at mode from the "mode selection screen" rather than what i specify on command line.  cliemts seem to run but screen just black.

**Comment by feifel** [comment]
I'm also interested in setting a different screen resolution. My galaxy not 3 has 1920x1080 but icons etc. are a bit to small. So I like to change the resolution to 960x520 which is the native resolution divided by 2. Unfortunately the "Select display resoution" Screen does not offer this resolution. Is there a way how I could enter a custom resolution. I was not able to call the XSDL command line described in the initial post. Do I need to install something else than this: 
https://play.google.com/store/apps/details?id=x.org.server&hl=de

**Comment by pelya** [comment]
It's 960x540, and version 1.11.12 supports that resolution through config
menu, please check for update on Google Play.

**Comment by PabloGN** [comment]
Hi, thank you, great work. I also tried to build Xorg for Android but your work is better.

One question: I have tried to start Xephyr but it tells:

Xephyr unable to use SHM XImages

I would like to use the whole desktop in a window.

xinit ~/.xinitrc.gn -- /usr/bin/Xephyr :1 -ac -geometry 1024x768

Does it have OpenGL your app?

I use Debian Kit, I think it could be a good idea to include its starting script, the bootstraping installation, etc. in XSDL. 

Thank you!

Pablo González Nalda
http://lsi.vc.ehu.es/pablogn/
UPV/EHU, Lenguajes y Sistemas Informáticos, Vitoria

**Comment by pelya** [comment]
No, it does not support OpenGL. If you need SHM extension, you'll have to
download libandroid.shmem.so from here:
https://github.com/pelya/cuntubuntu/tree/master/dist
and then launch Xephyr like this:
env LD_PRELOAD=/path/to/libandroid.shmem.so xinit <params...>
Also, it should work okay without SHM extension, did you specify proper
DISPLAY variable before launching it?

**Comment by marcemira** [comment]
Here's how it looks when i use 897x540 mode for my 960x540 display,
![xserver_xsdl](https://cloud.githubusercontent.com/assets/1788212/2675759/a66bb862-c122-11e3-956f-aaf709e64c0c.png)

In fact every res in the first row causes the same effect, but it work's great using the other resolutions, now using 1200x720 at 0.4, looks great, small although

**Comment by pelya** [comment]
This may happen because 897 is an odd number, I'll try to reproduce.

**Comment by marcemira** [comment]
can you force it to a next lower pair number?

**Comment by pelya** [comment]
I've published an update, which fixes odd numbers in the display resolution
list, could you please check?

**Comment by marcemira** [comment]
Pelya Thanks! In the first row most of resolution were odd, now only the native. I'm using v1.11.14. Cheers
![sdlx](https://cloud.githubusercontent.com/assets/1788212/2888970/820a419a-d514-11e3-99c4-d8585926c08c.png)
![sdlx2](https://cloud.githubusercontent.com/assets/1788212/2888973/854477cc-d514-11e3-9591-cbf7cc380501.png)

**Comment by pelya** [comment]
So, does this fix the weird display bug for you? You can also override
resolution using '-display Xres/XMMxYres/YMM', where XMM and YMM are
display physical size in millimeters, pass it as argument to XSDL command
line, you may change that command line by going to 'Change device config'
menu and selecring 'Installation location' -> 'Custom' .

**Comment by cbm755** [comment]
at least my original bug can now be closed (-display Xres etc...)

I can't comment on any of the other issues others have mentioned.

**Comment by rctan** [comment]
How do you get to the "Select Display Resolution" screen? This screen only shows up once when I first invoke the Xserver XSDL application. There's mention about "Change device config' menu, how do you get that menu? I am using Nexus 7 running Android 4.4.2. Thanks!

**Comment by pelya** [comment]
Kill XSDL using Android task manager, then start it again, it will show
that config menu for 3 seconds when starting - tap the screen, and select
new display resolution.

**Comment by rctan** [comment]
Got it! Thanks for your quick reply!

**Comment by pelya** [comment]
-screen option now works properly, starting from 1.11.14.
