### ISSUE TITLE
Change background.png

### ISSUE THREAD

**Issue by Tutueti** [pelya/xserver-xsdl#139]
Hello,

Is it possible to change the blue screen that shows up just after the resolution selection screen?
I found it to be a file on Android/data/x.org.server/files/background.png
I tried editing the image to just a solid red backgroud as I wanted, but whenever I open the app, it replaces it with the original.

Are there any means by which I could customize it?

**Comment by pelya** [comment]
Add '-nohelp' option to command line arguments in 'Change device
configuration' dialog.
You can also change the X server background image from your Linux by
running something like

xloadimage -onroot -fullscreen image.png

**Comment by Tutueti** [comment]
Thank you. It works well.

Any way of also changing the starting SDL screen image?

**Comment by pelya** [comment]
You'll need to recompile the app for that

**Comment by Tutueti** [comment]
Got It. Might not be worth the amount of work.

Thank you!
