### ISSUE TITLE
Clipboard does not work.

### ISSUE THREAD

**Issue by gety9** [pelya/xserver-xsdl#150]
Pelya hi,

Thank you for great project!

I've installed it on termux and connected via xsdl android app, everythings works except for clipboard (can't copy paste between xsdl app and other apps (browser, etc).

What could be the problem?

On same termux/tigervnc <> real vnc viewer set-up clipboard works fine. So i am confused what can be the reason.

**Comment by pelya** [comment]
You can copy text from Android clipboard to XSDL, use mouse wheel click to
paste it, Ctrl-V will not work.
Currently there's no possibility to copy text from XSDL to Android
clipboard.

**Comment by gety9** [comment]
@pelya 

Got it, thank you for fast reply, closing.
