### ISSUE TITLE
Custom Fonts don't work, part 2!

### ISSUE THREAD

**Issue by rctan** [pelya/xserver-xsdl#16]
Hi,

This is related to the closed issue "Custom Fonts don't work"
I followed your instruction to set the font path but when I performed an "xlsfonts -display [NEXUS 7 IP Address]:0" on the Linux PC, it did not see the new fonts. It listed these six fonts:

[root@DRSNexusTabletServer02 ~]# xlsfonts -display 192.168.42.129:0
-misc-fixed-medium-r-semicondensed--0-0-75-75-c-0-iso8859-1
-misc-fixed-medium-r-semicondensed--13-100-100-100-c-60-iso8859-1
-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso8859-1
6x13
cursor
fixed

I copied two fonts (10x20.pcf, 8x13.pcf) to the /sdcard/fonts folder. Any ideas why the X Server is not loading the fonts? Thanks in advance!

**Comment by pelya** [comment]
Are you sure you've put all files in correct places, and not misspelled
command line? Can you copy whole directory /usr/share/fonts/X11 from your
Linux onto SD card, and also check the logcat output when XSDL starts?
I'll update XSDL in a few weeks, and add an optional package with standard
X fonts, which will be installed into correct places.

**Comment by rctan** [comment]
I copied all the files/directories (fonts/misc, fonts/100dpi, fonts/encodings, fonts/misc, fonts/Type1, fonts/util) into /sdcard/fonts directory as you suggested. More fonts were loaded to the X Server this time but not the ones I was interested in. Even though the 10x20 and 8x13 fonts were in the /sdcard/fonts/misc directory, just like the 6x13 font. They were not loaded. I had the command " XSDL -fp /sdcard/fonts/100dpi/,/sdcard/fonts/encodings/,/sdcard/fonts/misc/,/sdcard/fonts/Type1/,/sdcard/fonts/util/" with no spaces.

**Comment by pelya** [comment]
I've added a package with many fixed fonts to the release 1.11.15, it should work out of the box.
