### ISSUE TITLE
How does the rendering process work？

### ISSUE THREAD

**Issue by foryoung2018** [pelya/xserver-xsdl#175]
I want to delve deeper into the details of this project. I have a grasp of OpenGL and some X11 protocols, but I haven't really found comprehensive information about the rendering data transfer between SDL and X Server. Is the project utilizing the Put Image protocol or Android Shared Memory?

In theory, rendering pixels doesn't necessarily require the SDL library, and basic bitmap drawing should suffice. Is this due to the effectiveness of OpenGL or Android Shared Memory, especially for supporting some X programs? 

I look forward to your response. Thank you.

**Comment by pelya** [comment]
SDL creates a screen buffer in memory. XSDL code copies from X screen
buffer to SDL screen buffer each frame, then SDL copies it into OpenGL
texture on each SDL_Flip.

Shared memory is for X apps to write directly to X screen buffer.

And XSDL does not support OpenGL for X apps, even though it uses GL ES
internally.

**Comment by foryoung2018** [comment]
Thanks,    I cant locate the code about : "XSDL code copies from X screen buffer to SDL screen buffer each frame"  Can you tell me?

**Comment by foryoung2018** [comment]
(*pGC->ops->PutImage) (pDraw, pGC, stuff->depth, stuff->dstX, stuff->dstY,
                           stuff->width, stuff->height,
                           stuff->leftPad, stuff->format, tmpImage);

go to where?

**Comment by pelya** [comment]
https://github.com/pelya/xserver-xsdl/blob/xsdl2/hw/kdrive/sdl/sdl.c

sdlMapFramebuffer sets the X display buffer

sdlShadowUpdate does SDL_flip

**Comment by hardBSDk** [comment]
> SDL creates a screen buffer in memory. XSDL code copies from X screen
> buffer to SDL screen buffer each frame, then SDL copies it into OpenGL
> texture on each SDL_Flip.
> 
> Shared memory is for X apps to write directly to X screen buffer.
> 
> And XSDL does not support OpenGL for X apps, even though it uses GL ES
> internally.
> […](#)

Can you document this in the README?

**Comment by pelya** [comment]
Done
