### ISSUE TITLE
Please make XServer XSDL available from F-Droid

### ISSUE THREAD

**Issue by rbalint** [pelya/xserver-xsdl#18]
I think it would be nice to be able to download XSDL from F-Droid. There are people with custom Android firmware who don't like installing Google Play but would happily use XSDL without compiling it.

**Comment by pelya** [comment]
You can download compiled app from my site:
http://libsdl-android.sourceforge.net/

I've published my sources, it's up to F-Droid guys to integrate them into
their build system.

**Comment by rbalint** [comment]
OK, now I have found the request for inclusion in their queue:
https://f-droid.org/forums/topic/droidphp-2/
Thanks for the software!
