### ISSUE TITLE
Device with soft buttons causes screen/input misalignment with onscreen keyboard

### ISSUE THREAD

**Issue by cbm755** [pelya/xserver-xsdl#19]
I tested xserver-sdl on a nexus 5 which has no hardware home button. It uses a small mabye 64 pixel bar at the button of the screen for home, back, etc.  I also enabled these softbuttons on my Note 8.  Observations:
1. xserver-sdl starts in full screen (both top and bottom bars move out of way). Input works correctly.
2. If I bring up onscreen keyboard (back button twice), then it appears but the soft home button bar comes back too.  this shifts the screen upwards by about 64 pixels. But input is not shifted so one has to touch about 64 pixels below the target.

My preference: show soft home all the time and have slighly smaller framebuffer for x.

**Comment by cbm755** [comment]
Here is the view w/o keyboard
![tmp_screenshot_2014-06-20-00-25-24-793606667](https://cloud.githubusercontent.com/assets/818622/3348222/a7c099d0-f91c-11e3-839a-55cc96e1f0c2.png)

Now I open the keyboard:
![tmp_screenshot_2014-06-20-00-25-38973471672](https://cloud.githubusercontent.com/assets/818622/3348229/d2658416-f91c-11e3-9889-b28a62caa43b.png)

**Comment by pelya** [comment]
If you press Back button again, it will hide the button bar, and the app
will be full-screen again. I will add an option to SDL settings to disable
immersive mode, and always show button bar.

**Comment by cbm755** [comment]
Yes that's right.  Pushing "back" to hide the keyboard returns to the usual state.  But its still a bug: while the keyboard is open, touch events don't line up with the display.  (Personally, I leave the keyboard open all the time.)

The option you describe sounds perfect for me, thanks.

**Comment by cbm755** [comment]
leaving "hide system navigation buttons / immersive mode" _unchecked_ works perfectly.

I will close this, although there is still a bug here if a user uses immersive mode and has keyboard open.  Re-open if you want.
