### ISSUE TITLE
blank screen after Alt-Tab

### ISSUE THREAD

**Issue by sunaku** [pelya/xserver-xsdl#2]
Hello,

I'm using XServer XSDL version 1.11.07 under Android 4.3.

When I switch to another app (using Alt-Tab) and then switch back, the XServer XSDL app's screen becomes blank (nothing is rendered).  Sometimes, after a random amount of switching to different apps, the XServer XSDL app's screen displays correctly again.

Thanks for your consideration.

**Comment by pelya** [comment]
Should be fixed in 1.11.09.

**Comment by sunaku** [comment]
Thanks, version 1.11.09 fixed the problem for me! :smiley_cat:
