### ISSUE TITLE
glxinfo/glxgears don't seem to work

### ISSUE THREAD

**Issue by killerkalamari** [pelya/xserver-xsdl#21]
```
# glxinfo
name of display: 127.0.0.1:0
Error: couldn't find RGB GLX visual or fbconfig

# glxgears
Error: couldn't get an RGB, Double-buffered visual

# fbset -fb /dev/graphics/fb0
mode "480x800-0"
    # D: 0.003 MHz, H: 0.006 kHz, V:  0.006 Hz
    geometry 480 800 480 2400 32
    timings 343500000 16 16 7 105 4 2
    rgba 8/24,8/16/8,8/0
endmode
```

Any ideas on this? I have a few mesa libraries installed, and I thought they should allow software rendering of OpenGL. Debian Wheezy.

**Comment by pelya** [comment]
glxgears work for me in Debian noroot, after installing mesa-utils and
libgl1-mesa-swx11 packages. I will add libgl1-mesa-swx11 to Gimp and to
Debian noroot apps, because they use libgl1-mesa-glx by default.

**Comment by killerkalamari** [comment]
Thank you, installing libgl1-mesa-swx11 worked perfectly!
