### ISSUE TITLE
xournal: pen input

### ISSUE THREAD

**Issue by cbm755** [pelya/xserver-xsdl#22]
I've tested 1.11.15, new options look great, thanks!

Strangely, I still cannot get nice pen input into xournal (dmgerman's -next branch) like I can on your gimp/inkscape app.  I've finally added your android-shmem binary, thinking that might be the problem but no improvement.  There is still _something_ different between gimp/inkscape app and xsdl-xserver...

The drawing lags behind the pen movement by something like 500ms, as observed in the packaged older version of xournal within your gimp/inkscape app.

**Comment by cbm755** [comment]
If you are interested in testing this too, here's a pre-compiled version (run src/xournal)  [http://people.maths.ox.ac.uk/macdonald/temp/xo-gimp-works.tar.gz].  Depends on "apt-get install  libgnomecanvas", possibly others, I installed it a long time ago, sorry.

1)  When I use this within gimp/inkscape app, the pen is pretty good (almost as good as direct framebuffer X).

2)  But when I use it in my chroot (connected to xserver-xsdl), its no better than the old packaged xournal (apt-get installable within gimp/inkscape).

**Comment by pelya** [comment]
Did you enable 'send multiple events per video frame' in mouse emulation
options in SDL settings?

**Comment by cbm755** [comment]
of course!

**Comment by cbm755** [comment]
I just double-checked again in gimp/inkscape app: its not perfect (compared to direct framebuffer) there is a small delay there too, but much better than in xserver-xsdl.

In xserver-xsdl, if I draw very fast spirals, the drawing can be delayed by 1 or 2 _seconds_.  In gimp/inkscape app, it always lags very slightly, at most 100ms (I guess) and seems independent of what I draw.

I've tested xserver-xsdl with and without "filter jitter for stylus/finger hover", "finger hover", "linear video filter": no difference.

**Comment by pelya** [comment]
To clarify - are you testing the same xournal build in both environments?

android-shmem should give rather big boost to performance. If you run
xournal from terminal, it will print debug logs to stdout, that's how you
may know that  android-shmem is actually used.

Gimp itself is kind of special - it has compile-time option to limit frame
rate and batch multiple drawing operations, I've recompiled it for the app,
so it does not redraw more often than once per 30 milliseconds, which makes
it more responsible. If you install Gimp inside Debian noroot app, it will
be slower.

**Comment by cbm755** [comment]
yes same build.  The tar file I linked to is it.  Compiled with debian compiler inside gimp/inkscape.

Yes shmem seems to be used (without it no logs to stdout, with it I see logs, they look about the same as in gimp/inkscape).

Xournal build is not statically linked so potential difference there between debian and fedora.

Re: "gimp itself is kind of special" do you mean "compile-time option" in the _gimp_ build or in the xserver-xsdl build?  If the latter, perhaps that explains the issue I see!

**Comment by pelya** [comment]
Nah, xserver is identical in both apps. Gimp itself (Linux app) was
recompiled.

**Comment by cbm755** [comment]
:(  I could recompile statically I guess...  not sure what else to try.

My other wild guess was this had something to do with ABS_MT_TOOL_X versus ABS_MT_POSITION_X... I notice when hacking on evdev for framebuffer that finger drags give lots of ABS_MT_TOOL_X rather than ABS_MT_POSITION_X events...  although that was finger not pen.

Framebuffer is very smooth with pen!  I think there might be merit to letting apps talk directly to Android's Linux Kernel via xf86-input-evdev/libevdev, and just use SDL for graphics rendering...  I'm not sure what is involved in such a setup though.  But Gimp might work better too.

There is an issue with lack of ABS_X events, reported here https://bugs.freedesktop.org/show_bug.cgi?id=80470, but I think I have a workaround, at least for GTK3 and modern touch aware toolkits...

**Comment by cbm755** [comment]
While I'm thinking about this, the benefit of using XSDL over fbdev for X is probably integration into android GUI.  For example, users get preferred keyboard.  Using fbdev X, you have to logout of X to switch Android apps.  On stock ROM with note 8, I had to reboot after each use too.  On CyanogenMod that is improved.
