### ISSUE TITLE
Audio settings?

### ISSUE THREAD

**Issue by tonigi** [pelya/xserver-xsdl#25]
There are two sections in the configuration...
- size of audio buffer and
- video settings

Are audio and video actually supported?

**Comment by pelya** [comment]
Audio is not supported. X11 protocol does not support audio anyway.

Video, well - if you can see anything at all at your screen, then it
probably is supported :)

**Comment by mittorn** [comment]
Use this: https://github.com/dront78/PulseDroid/tree/master/bin

**Comment by pelya** [comment]
Thanks for the tip, it looks easier than I expected. Maybe I'll have some
free time in a month to integrate this code.

**Comment by pelya** [comment]
Audio is supported in latest Debian noroot app, although it's quite buggy and laggy.

If you have root, you can use PulseAudio module-pipe-sink with output to the path /data/data/x.org.server/files/img/tmp/audio-out (create that .../tmp directory first).

Here's an example of PulseAudio config, replace file=/tmp/audio-out with file=/data/data/x.org.server/files/img/tmp/audio-out and save to /etc/pulse/default.pa in your Linux installation:
https://github.com/pelya/cuntubuntu/blob/master/dist/root/.config/pulse/default.pa

**Comment by ShapeShifter499** [comment]
Would this feature be added to 'Xserver XSDL' or is it just supported on 'debian noroot'?

**Comment by pelya** [comment]
XSDL supports it, but setting it up from Linux side is not trivial (but
very simular to PulseDroid), also it does not work over network, because I
was in a rush.

I recommend using PulseDroid in parallel with XSDL, because it at least has
a setup instruction.

**Comment by ShapeShifter499** [comment]
If XSDL supports it, it would would work great for chroot purposes. I could just mount /data/data/x.org.server/files/img/tmp inside my chroot and point pulseaudio to it. Pulsedroid would work for non-local audio.   I personally use "simple protocol strramer" for chroot audio right now. https://play.google.com/store/apps/details?id=com.kaytat.simpleprotocolplayer

**Comment by ShapeShifter499** [comment]
Just made the mount inside my chroot and pointed pulseaudio to it, works great!

**Comment by ShapeShifter499** [comment]
I mentioned about it at http://androidforums.com/threads/how-to-getting-audio-working-inside-a-chroot.924537/   I hope you don't mind
