### ISSUE TITLE
BT Mouse right click problem's.

### ISSUE THREAD

**Issue by ghost** [pelya/xserver-xsdl#27]
Hello again.
I have problem's with right click at my bt mouse when using xsdl.
It's open's a keyboard, because it's mapped as back key under android by default.
I wanna use it as right click under apps in xserver, not to open a keyboard.
So I tried to map this key to "UNKOWN" or "NO_REMAP" but after all, it's sends back key to android, and this not work.
If I map this key to something other, it's work's, but it's send's too this second key, what is problematic.
Device is Galaxy Tab 3 7.0 with 4.1.2 stock rom and blackhawk kernel.
I wanna say that I don't have this issue under Galaxy Tab 2 10.1 with CM11, blackhawk kernel too (but I think blackhawk kernel was deleted by cm updates, because I don't have overclocking after these).
So, suggestion - add the keymap that do nothing, but after all, this will don't send too anything to android.
Also, thank's for great app that make using linux under chroot more friendly than anything (or no, only framebuffer method is more friendly :P)

**Comment by pelya** [comment]
Blame Samsung and their half-wit Touchwiz. Starting from Android 4.0,
external mouse does not send Back key, it sends mouse buttons, but Samsung
reverted that. If they will ever upgrade firmware on your Galaxy Tab, this
should be fixed.
