### ISSUE TITLE
Is it possible to disable "buggy touchscreen detection"?

### ISSUE THREAD

**Issue by ghost** [pelya/xserver-xsdl#28]
I sometimes get this error, and after all, the XSDL is more unsuable... It's hard to use with mouse, with touch too.
It's possible to disable it? If yes, how?
Thank's.

**Comment by pelya** [comment]
When XSDL is just started, move the mouse a bit, then click it two times at
the same spot, this will disable error detection. Or tap with a finger in
the same spot.

The error happens on various MTK-based tablets, where the screen driver
sends fake finger hover movements, which jump for more than half of the
screen between real finger taps. Many other devices report mouse as if it's
a finger, and I didn't want to totally disable mouse hover movement (which
is what you're seeing when this error happens),  hence XSDL got this
half-wit error detection code.
