### ISSUE TITLE
When switching between the android applications xserver-xsdl hangs

### ISSUE THREAD

**Issue by vlvlbel** [pelya/xserver-xsdl#29]
Hi there!

At first, I would like to thank you for the good work.

There is an issue on my android 4.2 tablet: when switching between the android applications or when returning from the lock screen xserver-xsdl hangs. My tablet has 2Gb RAM. Maybe it has to do with lack of memory and I need to increase it at the expense of the swap partition, don't I?

Best regards,

**Comment by pelya** [comment]
No, XSDL does not use a lot of RAM.

I've seen this bug before, and tried fixing it, but had not much success
yet.

**Comment by pelya** [comment]
Should be fixed in 1.11.20

**Comment by vlvlbel** [comment]
02.01.2015 2:19, Sergii Pylypenko пишет:

> Closed #29 https://github.com/pelya/xserver-xsdl/issues/29.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/pelya/xserver-xsdl/issues/29#event-213342228.

Добрый день, Сергий!
С наступившим, здоровья, благополучия, мира!

Я установил на планшет (android 4.2) вашу сборку debian+gimp+inkscape на 
xserver-xsdl ещё до устранения бага #29.
Читал ваше сообщение о том, что приложение gimp+inkscape нельзя удалять 
из-за бага андроида в части юникс-сокета.
Скажите, как я могу обновить xserver-xsdl не удаляя debian+gimp+inkscape?

## 

С уважением,
Владимир Белоусов,
Республика Беларусь.

**Comment by pelya** [comment]
Пока что никак, я его обновлю на следующей неделе.

Можно поставить XSDL и GNURoot, запустить XSDL, внутри  GNURoot поставить
Gimp, и запускать его из командной строки:
DISPLAY=127.0.0.1:0 gimp
Будет правда медленнее работать.
