### ISSUE TITLE
crash on resolution change

### ISSUE THREAD

**Issue by sunaku** [pelya/xserver-xsdl#3]
Hello,

I'm using XServer XSDL version 1.11.07 under Android 4.3.

It crashes when I change the screen resolution in Android:

```
wm resize reset
wm density reset
```

Or:

```
wm resize 1920x1080
wm density 160
```

As a result, I lose my X session with errors like this:

```
xterm: fatal IO error 104 (Connection reset by peer) or KillClient on X server ":1"
Error: Can't open display: :1 
```

Thanks for your consideration.

**Comment by pelya** [comment]
What exactly is that "wm" command? I cannot find it on http://www.debian.org/distrib/packages
You cannot change resolution with xrandr, as far as I've tested it (but you can rotate/mirror your screen).

**Comment by sunaku** [comment]
The `wm` command is from Android shell (which you can access using **Android Terminal Emulator** app):

https://android.googlesource.com/platform/frameworks/base/+/master/cmds/wm/src/com/android/commands/wm/Wm.java

I become root and then run `wm resize 1920x1080 && wm density 160` to make better use of my Android's HDMI output (connected to my large computer monitor).  You can do the same thing using `adb` shell too.  See:

http://stackoverflow.com/questions/18500611/android-how-to-use-adb-shell-wm-to-simulate-other-devices

I'm not trying to use `xrandr`. :sweat_smile:  The problem is that after resizing Android with `wm` command, XServer XSDL crashes.

Thanks for your consideration.

**Comment by sunaku** [comment]
Sorry for the confusion: I should have written "reset" instead of "crash" because the app does not "force close". :sweat:  Instead, when switching to the app after a native Android resolution change, the app shows the SDL logo again and starts a new X display server (at the same address as last time).

**Comment by sunaku** [comment]
Good news: the bug seems to originate from SDL itself! :bug: I tried another SDL app for Android ([OpenTyrian](https://play.google.com/store/apps/details?id=com.googlecode.opentyrian)) and it exhibited the same bug: SDL would reset itself (and I would lose my progress in the game :game_die:) when Android's native display resolution was changed. :neckbeard:

**Comment by pelya** [comment]
Now it does not crash, starting from 1.11.20, it gracefully suicides and restarts itself. No easy way to fix that properly.
