### ISSUE TITLE
[Suggestion] Wrap mouse

### ISSUE THREAD

**Issue by fervi** [pelya/xserver-xsdl#30]
Hello!

I see - some games grab mouse (and you move a cursor into this program, and your android cursor not moving) - QIII4A or QI4A. It use Root for that option, and you can use your Mouse to play with this game

Maybe Xserver XSDL should use it? And for example ALT + CTRL release your mouse (like VirtualBox)

Fervi

**Comment by pelya** [comment]
I won't add root hacks like in QIII4A, sorry.
