### ISSUE TITLE
No hardware OpenGL rendering?

### ISSUE THREAD

**Issue by Mischa-Alff** [pelya/xserver-xsdl#31]
I'm running Archlinux ARM in a chroot (Linux Deploy) on my NVIDIA SHIELD tablet, which supports OpenGL 4.5. I've chosen the X Server option when starting Archlinux up. Everything runs fine, but when I run `glxinfo` in a terminal (via XServer XSDL), I get:

```
name of display: 127.0.0.1:0.0
Error: couldn't find RGB GLX visual or fbconfig
```

I'm not sure if this is XServer XSDL's fault, tell me if it isn't. What should I do to fix this?

**Comment by pelya** [comment]
XSDL does not provide accelerated OpenGL.

Android does not support desktop OpenGL, it supports an OpenGL subset
called GLES, and it's not possible to add hardware-accelerated OpenGL
simulation in an easy way. There was a library that could simulate OpenGL
using GLES, called glshim, but it's not finished yet, and only simulates
OpenGL 1.x.

**Comment by Mischa-Alff** [comment]
Applications running on NVIDIA Tegra K1 SoCs can make use of desktop OpenGL (as well as OpenGL ES).
But that doesn't matter, since (as you said), XSDL doesn't provide accelerated OpenGL.
Thanks.

**Comment by pelya** [comment]
Does Nvidia provide some extension Android API for desktop OpenGL? Do you
have a link to documentation.
They cannot just put libGL.so into /system/lib, you also need to hook it
into Android GUI somehow.

**Comment by twaik** [comment]
I think it can be useful: https://github.com/p3/regal . 

> Regal is a user-space OpenGL layer for OpenGL 2.x, 3.x, 4.x, Core contexts and ES 2.0. Regal implements OpenGL loading, emulation for ES and Core contexts and tools for debugging.

You can add this into project. But... Can KDrive use GLX or something? I heard about KAA - KDrive Accelleration Architecture.

**Comment by a1batross** [comment]
@pelya it's simple to acquire OpenGL on Tegra. Load libEGL and call eglGetProcAddress. 

But I don't know how it will work over GLX and how to translate it.

**Comment by Nixola** [comment]
Hi, sorry to bump but I would just like to say I'd really like OpenGL hardware acceleration added, for systems that do support it. Examples would be, as already noted, Tegra devices, or pretty much any PC running an x86 or x86_64 version of Android (Android-x86, RemixOS).
