### ISSUE TITLE
no armeabi libs

### ISSUE THREAD

**Issue by bigsupersquid** [pelya/xserver-xsdl#38]
many stock gingerbread devices like the one I'm using now are armeabi. google didn't stop armeabi support officially in favor of armeabi-v7a until ice cream sandwich.
I really enjoy this app.
my x86 build box has been out of commission for months or I'd not bother you with this issue.
I haven't been able to adapt the sdk or ndk for arm so no sdl build for rebuilding this myself for armeabi.
thanks for your work and for sharing source.

**Comment by pelya** [comment]
I was hoping armeabi died when HTC Evo was released in 2010. I'll include
ARMv5 into the next release.

**Comment by bigsupersquid** [comment]
thank you. It's appreciated, and I know of other legacy hardware users who woud like to try it out too.
I recently had to fallback to my armv6 phone when I killed my HTC Evo, which had been running your current version oh-so-smoothly. How ironic you mention that device.
