### ISSUE TITLE
hardware keyboard: up/down/right/left not working like exspected

### ISSUE THREAD

**Issue by fleixi** [pelya/xserver-xsdl#43]
i have plugged in a hardware keyboard and mouse from logitech (k260) and if i use the arrowkeys the mouse is moving in this direction. but i would to use them going up and down in textfiles....

**Comment by pelya** [comment]
Did you change anything in SDL config? There is an option to move mouse
with arrow keys, but it's disabled by default.

**Comment by fleixi** [comment]
You are right. I didnt know i could uncheck all mouse options and they wasnt well named for me. Now it is working perfect.
