### ISSUE TITLE
keyboard dont send "pipe/greater/smaller" key

### ISSUE THREAD

**Issue by fleixi** [pelya/xserver-xsdl#44]
I have some errors with my logitech k260 wireless keyboard:

The keys "-" and "ß" are switched and the keys "z" and "y" too. It could be easily be remapped in the xserver app.

But the "pipe" key isnt been recognised by xev so the key isnt working. The key is recognised by the app but if i try to remap it to an other key the new key isnt working too.

**Comment by pelya** [comment]
Should be fixed in 1.20.47
