### ISSUE TITLE
xrandr fails to change XServer DPI

### ISSUE THREAD

**Issue by sunaku** [pelya/xserver-xsdl#5]
Hello,

The resolution of XServer XSDL is too large on my Android device:

``` sh
$ xdpyinfo | grep resolution:
  resolution:    208x209 dots per inch
```

I get an error when lowering the resolution to 100 DPI using xrandr:

``` sh
$ xrandr --dpi 100
xrandr: Failed to get size of gamma for output default
```

How can I fix this? :worried:

Thanks for your consideration.

**Comment by pelya** [comment]
You should change DPI when the server starts, there is a startup dialog, which prompts you to change resolution and font scale, font scale is actually a DPI setting.

Xrandr is only half-implemented, just to stop applications from complaining about missing extension.

**Comment by sunaku** [comment]
Thanks! Choosing font scale `x0.3` gave me ~90 DPI, which was the closest to 100 DPI of all font scales. :smiley_cat:
