### ISSUE TITLE
Content of window is too small on Nexus 9

### ISSUE THREAD

**Issue by SuicSoft** [pelya/xserver-xsdl#52]
Hi,
XServer XSDL which i downloaded from the play store works properly but the content of the window is a little too small. Is there any way to make it bigger. Also there seems to be a delay of the mouse actions.

Nexus 9 WiFi 16GB November

**Comment by pelya** [comment]
Change font size during app start.

**Comment by SuicSoft** [comment]
Yeah, it's ok now
