### ISSUE TITLE
mouse wheel scroll not recognized

### ISSUE THREAD

**Issue by sunaku** [pelya/xserver-xsdl#6]
Hello,

In my chroot'ed Linux connected to XServer XSDL 1.11.09, running `xev` shows that mouse wheel scroll is 
recognized as mouse button 1.  Instead, mouse wheel scroll should be recognized as mouse buttons 4 and 5.

Please add support for mouse wheel scrolling inside XServer XSDL. :mouse:

Thanks for your consideration.

**Comment by pelya** [comment]
Fixed in 1.11.10

**Comment by sunaku** [comment]
It works well. :+1:  Thank you! :bow:
