### ISSUE TITLE
After the 5sec countdown the app keeps restarting several times.

### ISSUE THREAD

**Issue by dyharlan** [pelya/xserver-xsdl#62]
after the timeout showing the res and font scale used the app restarts with a Restarting please wait.... screen and it loops that many times.

**Comment by pelya** [comment]
What device is that?

**Comment by dyharlan** [comment]
Galaxy S II GT-I9100

**Comment by dyharlan** [comment]
This prob is reproducible starting with 0.11.31. 0.11.29 works fine

**Comment by JohnMH** [comment]
I can reproduce this on a DROID MINI and Nexus 5.

**Comment by 4aiman** [comment]
reproducible on Archos GamePad2

**Comment by joaopa00** [comment]
Same here with a HL-789 mini pc.

**Comment by petrskoda** [comment]
Hi - I have installed XSDL first on Motorola Droid 4 with LineageOS14 (nightly from half july about) and it worked well. But Then I decided to return to CM11 unofficial from april 2017 - it has also Lineage boot animation - namely the build cm_maserati-userdebug 4.4.4. KTU84Q, kernel 3.0.8-g1c0d238-dirty humtmtaro@buildbox #2 from 17.4.2017    - this system seems to be working well - but the xsdl instralled here permanently loops in restarting after countdown .   When I try exit it by BACK button it sometimes shows the blue scrren with DISPLAY instructions but I cannot connect to it from GNUROOT debian (using export DISPLAY=:0  .  But the same worked on LineageOS14.   What should i debug or which log would you like to see to help you identify the issue ?

I guess it may be problem with different directory handling on SDcard and /data - in later than CM11 versions it is more complicated, directories under /storage are linked to hexanumbered dirs and the individaul applications write to different cache structure ...

Anyway I would appreciate the hints how to get XSDL working ...

ajnstein

**Comment by 10110111** [comment]
I also reproduce this problem on Lenovo A328. If while counting down I tap the screen and select some options (even same as before), this restart loop sometimes stops, and then the X server works normally.

**Comment by SakiiCode** [comment]
I figured out that every time the server stops/crashes, the "display number" increases by 1. At launch, the number of restarts are the same. (It's likely, that tries each port consecutively, they are somehow occupied). This is very annoying because I have to go back to Linux Deploy every time, stop, set the Display Number, start. After a phone reboot, it resets to 0. 
Please fix this

**Comment by CJeffyB** [comment]
I also am experiencing this.  The number of restarts increases by 1 each time I run the app.  Upon a reboot, it resets back to zero.
I can do whatever is needed to assist troubleshooting.
Device is an Acer R11 Chromebook.

**Comment by FTWJAY** [comment]
Running a pixel 3 using v9 pie in getting the same problem. Xlds just keeps looping with no error messages. I have set the DISPLAY before and after trying to launch but I get the same problem. I'm using UserLand and just want to launch lxde. Any thoughts?

**Comment by luongthomas** [comment]
I'm experiencing this too, I've got a Moto X4 running Pie

**Comment by Noobie000** [comment]
Same here
My Mi Mix 2s on Android 9 keeps getting the restarting loop

**Comment by binlive** [comment]
Hi!
Restaring loop on Galaxy S9+ Android 9..

**Comment by iacobucci** [comment]
Yeah on a OnePlus 3 running android Pie it does the same thing, i guess its a problem with Android 28 SDK or something... Please @pelya fix this!

**Comment by dron1885** [comment]
Same here, Galaxy A8, Android 9.0.

**Comment by riban-bw** [comment]
Still doing it 3 years later! Had anyone investigated the cause? It renders the app unusable, which is a shame.

I just noticed the screen resolution was set to a bad value. Selected native resolution and it is now working. Time will tell if this resolves my issue.

**Comment by berkay-repos** [comment]
@riban-bw What about the font-size? Do you use additional fonts the app offers?

**Comment by railgung** [comment]
reporting the problem on a xiaomi redmi note 7

**Comment by rubin110** [comment]
Seeing this problem with a Pixel 3 XL running stock Android 9.

**Comment by h0tk3y** [comment]
I faced this issue on a Samsung Galaxy Note 9 running Android Pie, too.

**Comment by tuxgirl** [comment]
Having this issue on Galaxy tab s4. I am trying to use native resolution, so I don't think it's a resolution issue.

**Comment by erfan-azhdari** [comment]
Same issue on Samsung galaxy a50 and a30 (android 9 pie).
But works fine in older devices (Sony Xperia Z1 using android 5.0)

**Comment by edanaher** [comment]
I saw the discussion on #97, and sure enough, downloading the current version from Google Play gives me a functioning X server on an (original) Pixel running Android 10.

It may have taken some time, but thanks @pelya for getting it working again!

**Comment by pelya** [comment]
Okay, thanks. Fixer in 1.20.41.
