### ISSUE TITLE
Colors wrong (in some software)

### ISSUE THREAD

**Issue by ids1024** [pelya/xserver-xsdl#69]
I am trying to use this to run [sent](http://tools.suckless.org/sent) on my phone. It is working, except that the colors are wrong (as is visible in the picture below). I have set xserver-xsdl to use 24-bit color, since sent requires that.

![screen](https://cloud.githubusercontent.com/assets/2263150/15271101/3424bd0e-19ee-11e6-8e62-079a40f36cf4.png)

The slide should be showing the [Mask of Agamemon](https://en.wikipedia.org/wiki/Mask_of_Agamemnon#/media/File:MaskOfAgamemnon.jpg), which is gold.

What I don't understand is that some other software (like sxiv) works fine in xserver-xsdl, displaying the same image with correct colors.

**Comment by pelya** [comment]
Looks like a bug in sent. XSDL has inverted pixel format, compared to PC,
but all applications handle this fine.

**Comment by ids1024** [comment]
It seems you're right; changing 3 lines in sent fixes it, though that is a hack reversing it rather than properly detecting the display. I'll see if I can find a proper way and submit a patch to sent.
