### ISSUE TITLE
android keyboard backspace

### ISSUE THREAD

**Issue by alexcohn** [pelya/xserver-xsdl#7]
Using xserver-xsdl with [Linux deploy](https://github.com/meefik/linuxdeploy). Great respect, and in many aspects this mixture works great. One strange issue: backspace in Android keyboard does not work (neither in xterm, nor in libreoffice writer). As workaround, I can open one on-screen key, and remap it to BACKSPACE.

**Comment by pelya** [comment]
You need to use a different Android keyboard, because some keyboards expect
an Android text edit widget, which is not present here.
Backspace is working while using Samsung's stock keyboard, Hacker's
Keyboard, Anysoft  keyboard, and Multiling keyboard beta, that's just ones
that I've tested.

**Comment by alexcohn** [comment]
Thanks, hacker's kb works like charm. The problematic one is the stock AOSP 4.2.2 keyboard.

**PS** you mentioned multi-language keyboards, how far is support for any of these?

**Comment by pelya** [comment]
It only supports english key layout, and that's not easy to fix. I'll try
to think up some method for syncing with Android clipboard to be able to
copypaste non-English symbols.

**Comment by alexcohn** [comment]
That would be great. Btw, it would be fun to share the clipboard (ctrl-c ctrl-v) with Android, actually. 

I'd love to find a useable solution for the software keyboard (for the insertion point to be conditionally panned half-screen up, to guarantee the user actually will see what she types), but this should probably be left for our grandchildren take care of, as an elementary school homework.

On the other hand, hardware mouse poses another challenge: the system "arrow" pointer shows up, and it is not synchronized with the Linux soft pointer (which changes its shape, as dictated by the window under it). I'd love to see only soft pointer, but this requires patches to system libraries, if not worse.

**Comment by pelya** [comment]
Kind of fixed - starting from version 1.11.14,  when you input text using non-English keyboard, XSDL now copies each symbol into clipboard, and sends Ctrl-V keycodes, which pastes the symbol in most apps. This is hacky but somehow works, in all apps except terminal.
