### ISSUE TITLE
Audio not working.

### ISSUE THREAD

**Issue by KoukiShichirou** [pelya/xserver-xsdl#70]
Hello.
My device is amami, xperia z1 compact.
I have Debian in chroot (linux deploy). I exported pulse like that:
export PULSE_SERVER=tcp:127.0.0.1:4712
But it's not working :/ Also I have gstreamer installed.

**Comment by jcjordyn130** [comment]
try export PULSE_SERVER=tcp:localhost:4712

**Comment by pelya** [comment]
Should be fixed in 1.20.41
