### ISSUE TITLE
24BPP mode not working (properly)

### ISSUE THREAD

**Issue by wyatt8740** [pelya/xserver-xsdl#72]
I'm using the version from google play.  I get something rather like this whenever I start in 24bpp mode. 16bpp works fine.

![screenshot 1](http://i.imgur.com/5Cj28LY.png)

![screenshot 2](http://i.imgur.com/LD9ahun.png)

Nexus 6, android 5.0.1, if it matters any. If you need more info, I can give it.

**Comment by pyc0de** [comment]
I'm having troubles with 24bpp mode too on Nexus 7 2013.

**Comment by wyatt8740** [comment]
hm, so it's not just me; good. Too bad it's not on f-droid so I can easily downgrade.

**Comment by pelya** [comment]
Here are old releases:
https://sourceforge.net/projects/libsdl-android/files/apk/XServer-XSDL/
I only have Nexus 7 2012. I'll try to reproduce on emulator, but I don't
know when I'll have enough free time to fix bugs in this app. Probably this
autumn.

**Comment by pelya** [comment]
Should be fixed in 1.20.47
