### ISSUE TITLE
Linux mouse lags behind the android cursor

### ISSUE THREAD

**Issue by joaopa00** [pelya/xserver-xsdl#78]
As said in the title, linux mouse lags behind the android cursor. That makes appear two cursors for a short time. That's quite annoying.

**Comment by iacobucci** [comment]
I think thats because the sdl layer runs at a slower frame rate, and while this cant be fixed you could try to make the android global mouse pointer transparent followind this guide: https://daniel-baker.photography/asus-fonepad-7-change-mouse-cursor/

**Comment by pelya** [comment]
Should be fixed in 1.20.47
