### ISSUE TITLE
hardware keyboard: layout messed-up

### ISSUE THREAD

**Issue by ikcalB** [pelya/xserver-xsdl#79]
Using `Linux Deploy` (debian jessie 8u6, on HUAWEI MediaPad M2 10.0) with my bluetooth keyboard `Rapoo E6100` (German Keyboard layout) I encounter the following issue:
(I have installeed `Hacker's Keyboard` from PS already)

- Keyboard works normal for android, all keys correct. (although some keys like `ˋ` seem to be UTF8 rather than ASCII - found this when trying to quote code here @ github)
- in XServer, several keys have the same keycodes, tested using `xev` (i.e. <kbd>Shift+6</kbd> and <kbd>Shift+7</kbd>)
- some keys have completely random UTF8 Keycodes (some Cyrillic characters, or whatever)

**Comment by deb75** [comment]
Same issue with bluetooth keyboard ej-bt230 (samsung) and samsung note 10.1 2014 Ed. (Android 7).

Keyboard works normally on the android terminal, but linux-deploy and Xserver it is messed-up, mainly some keys do not correspond

**Comment by deb75** [comment]
It seems to be difficult to make a physical azerty keyboard work with android + xserver-xsdl + debian(linux-deploy) when it is configured with a non US layout.

But when the keyboard is configured with a US layout on the android side, it becomes much more usable
within xserver-xsdl + debian(linux-deploy). You can indeed use setxkbmap to reconfigure it with another layout (fr for I), there are still some missing or not working keys though.

The annoying part is that one has to configure the keyboard with a US layout, on the android side each time one wants to use it with xserver-xsdl + linux-deploy (probably not debian specific).

Could this be improved ?

Regards

**Comment by jfu334** [comment]
I'm also affected by this, any news?

**Comment by pelya** [comment]
Should be fixed in 1.20.47
