### ISSUE TITLE
Unpacking files fails on x86 based Android tablet

### ISSUE THREAD

**Issue by perpe** [pelya/xserver-xsdl#8]
Hello pelya,

I own an ASUS MeMO Pad FHD with x86 CPU. The Play Store version of Xserver xsdl fails unpacking the needed files. I downloaded the XServer-XSDL-1.11.09-24bpp.apk from sf and this version works (maybe only with the ARM emulation, that my tablet owns)

**Comment by pelya** [comment]
This version does not support x86, please try to use the version from
Google Play. I'll update 24bpp version in a few days.

**Comment by perpe** [comment]
I tried the Play Store version, but it fails on unpacking the files.
I know that the sf version doesn't support x86, but my x86 tablet supports arm, that's why it works. ;)
The Play Store version gives only an error, failed unpacking the files, please reinstall the app (or something like that) Reinstalling it gives the same error.

**Comment by pelya** [comment]
I was sure I've fixed that bug, I'll check again.

**Comment by perpe** [comment]
Oh, I see, you have uploaded a new version. I will try it :-)

Edit: works, many thanks for the quick fix! :-)

Edit2: Oh no, no update, my fault. It shows me an update, because I've installed the older version. After clearing the data same error like before "Cannot unpack data files, please reinstall the app"

**Comment by pelya** [comment]
I've tested it on X86 emulator, and version 1.11.11 extracts data files
without errors, there's not much else I can do to test.

**Comment by perpe** [comment]
Thank you. I've looked into your code. Maybe the error is in the file commandergenius/tree/sdl_android/project/java/MainActivity.java, line 967. You use  android.os.Build.CPU_ABI and  android.os.Build.CPU_ABI2 for the binary extraction. On x86 devices with preinstalled Android the ABI2 is set to armeabi-v7a (is needed for Intel's ARM emulation)

But, I will look closer into it this weekend, if I find the time.

**Comment by pelya** [comment]
Yes, this place of code indeed contains bug - it first extracts x86
binaries, then it overwrites them with armeabi-v7a binaries.
I've fixed that, could you please check this build:
http://sourceforge.net/projects/libsdl-android/files/tmp/XServer-XSDL-1.11.12.apk

**Comment by perpe** [comment]
Great! It works. I pulled the xhost binary to my laptop, readelf shows the right x86 header (Intel 80386), confirms that it works without the Intel ARM emulation :)
Can I hope to see the 24bpp for x86 soon?

**Comment by pelya** [comment]
Here:
http://sourceforge.net/projects/libsdl-android/files/apk/XServer-XSDL/XServer-XSDL-1.11.12-24bpp.apk
I want to implement one small feature before updating it on Google Play
though.

**Comment by perpe** [comment]
Many thanks! Installed and it works :-)
