### ISSUE TITLE
Actual mouse support

### ISSUE THREAD

**Issue by Nixola** [pelya/xserver-xsdl#81]
I would like to see an option to "disable" mouse emulation, allowing one to use an actual, physical mouse (which could be connected via Bluetooth, USB OTG, etc). I tried several mouse emulation settings and the closes I could find is tablet mode, but while it makes the X mouse move "together" with the pointer it also makes it a bit offset, which is a bit annoying; I also see a lack of an actual right-click support, maybe the "physical key" setting for right click emulation could be expanded to include mouse buttons as well?

**Comment by NHellFire** [comment]
Proper mouse support is definitely needed, especially now that most devices support HDMI out, so could be used as a fully functional desktop with an external keyboard and mouse.

**Comment by pelya** [comment]
Should be fixed in 1.20.47
