### ISSUE TITLE
XServer XSDL should not be resizable on Android 7.0+

### ISSUE THREAD

**Issue by farmerbb** [pelya/xserver-xsdl#82]
Currently XServer XSDL is allowed to be put into multi-window mode on Android 7.0+, which causes issues:

* X server won't actually start if the app is in splitscreen mode
* Window can't be dragged around in freeform mode

Since this X server implementation simulates a fullscreen X display anyway, the app should be disallowed from running in multi-window by applying one of the following fixes:
* Adding ```android:screenOrientation="landscape"``` to the launcher activity entry in the manifest
* Upgrading to ```targetSdk 25``` and adding ```android:resizeableActivity="false"``` to the launcher activity entry in the manifest

**Comment by NHellFire** [comment]
It would be better to support multiwindow properly, so that it's usable with Samsung DeX. Which would allow it to be used fullscreen on an external monitor on supported Samsung devices.

https://developer.samsung.com/samsung-dex/how-it-works

**Comment by pelya** [comment]
Fixed in 1.20.41
