### ISSUE TITLE
Emulate mouse wheel on touchscreen?

### ISSUE THREAD

**Issue by rsidd** [pelya/xserver-xsdl#9]
Awesome app, I am using it to write this comment in firefox in a chroot on my android tablet, I have tweaked the settings until I am happy with the touchscreen, have given it five stars on the market. 

Prior to this I used jump desktop (vnc), and it has a nice feature that dragging with two fingers emulates a mouse wheel.  Any chance of including that?  It would be the last missing piece to make this thing perfect for me.  Ideally, drag down with two fingers = scroll page up, and vice versa (different from standard mouse wheel behaviour, but similar to how one drags on touchscreens).

**Comment by pelya** [comment]
Touch with two fingers will send right mouse button click, that will
interfere with such mouse wheel gesture.
One of ways to accomplish that would be to send right mouse click you
releasing fingers, instead of immediately.
How does Jump Desktop send right mouse click?

**Comment by rsidd** [comment]
Ah, I reconfigured right mouse click to long-press (1 sec), which was how
jump desktop did it...

I was also going to ask about middle mouse click (useful but not essential).

On Tue, Feb 18, 2014 at 12:51 AM, Sergii Pylypenko <notifications@github.com

> wrote:
> 
> Touch with two fingers will send right mouse button click, that will
> interfere with such mouse wheel gesture.
> One of ways to accomplish that would be to send right mouse click you
> releasing fingers, instead of immediately.
> How does Jump Desktop send right mouse click?
>

**Comment by pelya** [comment]
Right mouse click is not supported at all at the moment.

**Comment by rsidd** [comment]
You mean middle click?  Right click works fine...

Some sort of mousewheel solution would be great.  If not two finger drag,
maybe hold-and-drag, or something?

**Comment by pelya** [comment]
I guess it will be two-finger drag, because hold-and-drag is reserved for
drag&drop with left mouse button.
Anyway, I won't implement that quickly, in two weeks maybe.

**Comment by rsidd** [comment]
Two weeks is plenty quick -- thanks!

**Comment by pelya** [comment]
Fixed in 1.11.12
