### ISSUE TITLE
External keyboard issue

### ISSUE THREAD

**Issue by salvomic** [pelya/xserver-xsdl#92]
I'm using Xserver XSDL with GNURoot Debian 8.10 and a Microsoft Wedge Mobile keyboard (bluetooth), whose layout is Italian in EKH (External Keyboard Helper for Android), and a wireless mouse. Both keyboard and mouse runs ok in my tablet Android 7.

I'm using xlde desktop. In xterm (or also emacs) I can't type the slash (/, over 7 key): this is nowhere among the keys. . 
Also I've issue with other keys: { } ...
I think the Server XSDL doesn't use the EKH layout or mix-in US and IT layout...
Any help?

***
**Edit**: 
a workaround is to revert to the internal Android Italian keyboard: it works in XSDL, but in Debian console the layout is incorrect and it is better to use EKH again.

**Comment by salvomic** [comment]
I've now a similar problem in Gemini by Planet Computers (Android 7.1): all is ok with its keyboard and the Italian layout, but not in graphic mode (XTerm in Openbox of Termux Desktop and that of GNURoot Debian) using XSDL as server. In the Gemini the keyboard miss the dash key ("-"), not the slash: it is nowhere also!
Please, could you tell me if it could be a problem with XSDL server fonts or keyboard layout?

**Comment by pelya** [comment]
Should be fixed in 1.20.47
