### ISSUE TITLE
Sending touch input directly

### ISSUE THREAD

**Issue by SDkie** [pelya/xserver-xsdl#98]
Hi, 

Is it possible to send the touch input directly to the application and not use the touch screen as a mouse?
Ex: Touching on the close application icon will close the application and user don't have to move the screen cursor to that icon and then sending right-click action.

Sorry, I know maybe I am asking too much. But only because of this feature I have to use windows OS instead of Linux :(

**Comment by pelya** [comment]
Press 'Change device config' butt on during app start, select 'Mouse
emulation' -> 'Mode' -> 'Desktop'
