### ISSUE TITLE
XServer is restarting itself on Android 9.0 (LineageOS 16, Xiaomi Mi6)

### ISSUE THREAD

**Issue by memegauste** [pelya/xserver-xsdl#99]
I assume this is bug caused by XSDL not compatible with new android versions:
https://github.com/pelya/xserver-xsdl/issues/97

So I hope you will find some time to try to port XSDL to new NDK.

Question not releated to the issue:
Just curious, we use old base of Xorg, yeah? What about if we used new Xorg base?
It could change anything?

Thanks

**Comment by MathiasMagnus** [comment]
I encountered this issue as well, when trying to mix'n'match UserLAnd and XSDL. Any effort put into this is much appreciated.

**Comment by ShamrockLee** [comment]
I encounter this issue on Android 9, too.

**Comment by Danct12** [comment]
I am currently using XServer XSDL alongside with Linux Deploy on LineageOS 16 (Xiaomi Redmi 4X) and it appears that it works fine for me.

Except for the integrated PulseAudio, which does not appear to work.

![2019-10-21-100408_1280x720_scrot](https://user-images.githubusercontent.com/19162768/67173867-4f4f3a80-f3ea-11e9-8648-75240da035dd.png)

Android 28 = Android 9.0

**Comment by JanuszChmiel** [comment]
But there is much more interesting aspect of yours post.
Which rooting strategy did you used to get access to yours phone so you can run Linux deploy as root user?
Modern smart phones are very securely and robustly secured against known simple rooting apps which are simply installed to Android. New king root, kingroot and others very often do not work on modern devices.
Even such cheap phones like Blackview A5 are very professionaly secured, encrypted. Lenovo tablets have encryption enabled by default and checkbox can not be simply unchecked. They have cncrypted their devices to prevent clever people to unplug flash internal chip and read data externally outside The device.
Samsung Android kernel developers are using special real time RAM kernel protection. So really, Linux deploy is super, but how to safely root newest device is very complex challenge.
No every stock firmware is reliable and safe. Some firmwares can break The device or some special proprietary kernel device drivers are not available.

**Comment by Danct12** [comment]
That strategy is called bootloader unlock and TWRP + Magisk.

**Comment by JanuszChmiel** [comment]
Ok. I will need to plea some ssighted assistant to get this tool to work properly. I will test it on my older cheap phone. I will start with unlocked boot loader if somethink will go wrong to be able to recover The phone.

**Comment by pelya** [comment]
Fixed in 1.20.41
